/* eslint-disable react-hooks/set-state-in-effect, @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, ChartNoAxesCombined, CirclePlus, Download, FileText, LayoutDashboard, LibraryBig, Pencil, Search, Sparkles, Trash2, Upload, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ApplicationRecord, CATEGORIES, STATUSES, calculateStats, emptyApplication } from "@/lib/application";
import { toCsv } from "@/lib/csv";
import { JobImportDialog } from "@/components/job-import-dialog";
import { ResumeStudio } from "@/components/resume-studio";

const demo: ApplicationRecord[] = [
  { ...emptyApplication(), id:"demo-1", company:"星云科技", position:"用户运营", category:"用户运营", location:"上海", status:"面试", appliedDate:"2026-09-16", deadline:"2026-09-30", source:"公司官网", channel:"官网", resumeVersion:"运营版 v3", description:"负责用户增长活动、生命周期运营与数据复盘。", requirements:"商业分析或相关专业，具备数据意识和沟通能力。", companyIntro:"面向年轻用户的数字生活服务平台。", interviewExperience:"一面重点讨论用户分层和活动复盘。", preparationNotes:"准备一个完整的用户增长案例。", notes:"9 月 20 日二面", createdAt:"2026-09-16T06:00:00Z", updatedAt:"2026-09-18T06:30:00Z" },
  { ...emptyApplication(), id:"demo-2", company:"远见咨询", position:"商业分析师", category:"商业分析", location:"北京", status:"已投递", appliedDate:"2026-09-12", source:"实习僧", channel:"招聘平台", resumeVersion:"商业分析版 v2", description:"支持行业研究、经营分析与策略项目。", requirements:"熟练使用 Excel、SQL，逻辑清晰。", notes:"一周后跟进", createdAt:"2026-09-12T06:00:00Z", updatedAt:"2026-09-17T03:20:00Z" },
  { ...emptyApplication(), id:"demo-3", company:"青禾内容", position:"内容策略运营", category:"内容运营", location:"杭州", status:"待投递", appliedDate:"", deadline:"2026-09-25", source:"公众号", resumeVersion:"", description:"负责内容策略、作者运营及内容效果分析。", createdAt:"2026-09-08T06:00:00Z", updatedAt:"2026-09-16T07:00:00Z" },
];
const nav = [{id:"dashboard",label:"数据概览",icon:LayoutDashboard},{id:"applications",label:"岗位与投递",icon:BriefcaseBusiness},{id:"library",label:"岗位资料库",icon:LibraryBig},{id:"resumes",label:"简历工作台",icon:FileText}];
const statusStyle: Record<string,string> = {"待投递":"bg-slate-100 text-slate-700","已投递":"bg-blue-100 text-blue-700","笔试":"bg-violet-100 text-violet-700","面试":"bg-amber-100 text-amber-800","等待结果":"bg-cyan-100 text-cyan-800","获得Offer":"bg-emerald-100 text-emerald-700","已拒绝":"bg-rose-100 text-rose-700","已结束":"bg-zinc-100 text-zinc-600"};

async function requestJson(url:string, options?:RequestInit): Promise<any> {
  const response=await fetch(url,options); const body:any=await response.json();
  if(!response.ok) throw new Error(body.error||"操作失败，请稍后重试"); return body;
}

export default function JobCompass(){
  const [items,setItems]=useState<ApplicationRecord[]>([]);
  const [active,setActive]=useState("dashboard"); const [loading,setLoading]=useState(true);
  const [notice,setNotice]=useState(""); const [query,setQuery]=useState(""); const [status,setStatus]=useState("全部状态");
  const [category,setCategory]=useState("全部类别"); const [location,setLocation]=useState("全部地点"); const [sort,setSort]=useState("updated");
  const [editing,setEditing]=useState<ApplicationRecord|null>(null); const [detail,setDetail]=useState<ApplicationRecord|null>(null);
  const [removing,setRemoving]=useState<ApplicationRecord|null>(null); const [saving,setSaving]=useState(false);
  const [importOpen,setImportOpen]=useState(false); const [optimizeJob,setOptimizeJob]=useState<ApplicationRecord|null>(null);
  useEffect(()=>{requestJson("/api/applications").then((data)=>setItems(data)).catch(()=>{setItems(demo);setNotice("数据库暂时不可用，当前仅显示明确标注的演示数据；演示数据不会被当作真实 AI 结果或自动保存。")}).finally(()=>setLoading(false))},[]);
  const filtered=useMemo(()=>items.filter(x=>(!query||[x.company,x.position,x.location,x.notes].join(" ").toLowerCase().includes(query.toLowerCase()))&&(status==="全部状态"||x.status===status)&&(category==="全部类别"||x.category===category)&&(location==="全部地点"||x.location===location)).sort((a,b)=>sort==="company"?a.company.localeCompare(b.company,"zh-CN"):sort==="applied"?b.appliedDate.localeCompare(a.appliedDate):b.updatedAt.localeCompare(a.updatedAt)),[items,query,status,category,location,sort]);
  const stats=calculateStats(items); const locations=[...new Set(items.map(x=>x.location).filter(Boolean))]; const categories=[...new Set(items.map(x=>x.category).filter(Boolean))];
  const reload=async()=>{const fresh=await requestJson("/api/applications");setItems(fresh)};
  const save=async(record:ApplicationRecord,keepOpen=false)=>{setSaving(true);try{const saved=await requestJson("/api/applications",{method:record.id&&!record.id.startsWith("demo-")?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(record)});setItems(old=>record.id&&!record.id.startsWith("demo-")?old.map(x=>x.id===record.id?saved:x):[saved,...old.filter(x=>x.id!==record.id)]);if(!keepOpen)setEditing(null);setNotice("岗位已保存");return true;}catch(e){setNotice(e instanceof Error?e.message:"保存失败");return false}finally{setSaving(false)}};
  const remove=async()=>{if(!removing)return;try{if(!removing.id.startsWith("demo-"))await requestJson(`/api/applications?id=${removing.id}`,{method:"DELETE"});setItems(old=>old.filter(x=>x.id!==removing.id));setNotice("记录已删除");setRemoving(null);}catch(e){setNotice(e instanceof Error?e.message:"删除失败")}};
  const changeStatus=async(item:ApplicationRecord,next:string)=>{const changed={...item,status:next};setItems(old=>old.map(x=>x.id===item.id?changed:x));if(!item.id.startsWith("demo-"))try{await requestJson("/api/applications",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(changed)})}catch(e){setNotice(e instanceof Error?e.message:"状态更新失败")}};
  const exportCsv=()=>{const blob=new Blob([toCsv(filtered)],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`求职记录-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);setNotice(`已导出 ${filtered.length} 条记录`)};
  return <main className="min-h-screen bg-[#f4f7fb] text-[#172033]">
    <header className="sticky top-0 z-20 border-b border-[#dfe6ef] bg-[#0d2547] text-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-4 py-3 lg:px-8"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#2dd4bf] text-[#0d2547]"><BriefcaseBusiness size={21}/></span><div><p className="text-lg font-semibold leading-tight">求职航标</p><p className="hidden text-xs text-blue-100 sm:block">把每一次申请变成可复用的经验</p></div></div><Button className="bg-[#2dd4bf] text-[#0d2547] hover:bg-[#5eead4]" onClick={()=>setImportOpen(true)}><CirclePlus/>新增岗位</Button></div></header>
    <div className="mx-auto grid max-w-[1500px] lg:grid-cols-[225px_minmax(0,1fr)]">
      <aside className="hidden min-h-[calc(100vh-65px)] border-r border-[#dfe6ef] px-4 py-7 lg:block"><nav className="space-y-1">{nav.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setActive(id)} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium ${active===id?"bg-[#dff8f3] text-[#08796b]":"text-slate-600 hover:bg-white"}`}><Icon size={18}/>{label}</button>)}</nav><div className="mt-8 rounded-2xl border border-[#d9e2ee] bg-white p-4"><Sparkles className="mb-3 text-[#08796b]" size={20}/><p className="font-semibold">AI 可选接入</p><p className="mt-1 text-sm leading-6 text-slate-500">未配置 API 时，岗位、投递和简历的手动管理仍可正常使用。</p></div></aside>
      <section className="min-w-0 px-4 py-6 lg:px-8">
        <div className="mb-5 flex gap-2 overflow-x-auto lg:hidden">{nav.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setActive(id)} className={`flex shrink-0 items-center gap-2 rounded-full px-4 py-2 text-sm font-medium ${active===id?"bg-[#0d2547] text-white":"bg-white text-slate-600"}`}><Icon size={16}/>{label}</button>)}</div>
        {notice&&<div className="mb-5 flex items-center justify-between rounded-xl border border-[#bce9e1] bg-[#e9fbf7] px-4 py-3 text-sm text-[#07675c]"><span>{notice}</span><button aria-label="关闭提示" onClick={()=>setNotice("")}><X size={16}/></button></div>}
        {active==="dashboard"&&<Dashboard items={items} stats={stats} open={(x)=>setDetail(x)} loading={loading}/>}
        {active==="applications"&&<><PageTitle eyebrow="APPLICATIONS" title="岗位与投递" desc="新增岗位不代表已经投递；状态与实际使用的简历会分别记录"/><FilterBar query={query} setQuery={setQuery} status={status} setStatus={setStatus} category={category} setCategory={setCategory} location={location} setLocation={setLocation} sort={sort} setSort={setSort} locations={locations} categories={categories} exportCsv={exportCsv} importCsv={()=>setImportOpen(true)}/><ApplicationList items={filtered} loading={loading} open={setDetail} edit={setEditing} remove={setRemoving} changeStatus={changeStatus}/></>}
        {active==="library"&&<Library items={filtered} open={setDetail}/>}
        {active==="resumes"&&<ResumeStudio jobs={items} initialJob={optimizeJob} onInitialJobHandled={()=>setOptimizeJob(null)} onUseVersion={async(job,version)=>{await save({...job,resumeVersion:version.title,resumeVersionId:version.id});setNotice("已关联为这次投递实际使用的简历版本")}}/>}
      </section>
    </div>
    <ApplicationForm value={editing} close={()=>setEditing(null)} save={save} saving={saving}/>
    <Detail value={detail} close={()=>setDetail(null)} edit={x=>{setDetail(null);setEditing(x)}} optimize={x=>{setDetail(null);setOptimizeJob(x);setActive("resumes")}}/>
    <JobImportDialog open={importOpen} onOpenChange={setImportOpen} onSaved={reload} saveOne={save}/>
    <AlertDialog open={!!removing} onOpenChange={open=>!open&&setRemoving(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除这条投递记录？</AlertDialogTitle><AlertDialogDescription>{removing?.company} · {removing?.position} 的岗位资料也会一起删除，此操作无法撤销。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={remove} className="bg-rose-600 hover:bg-rose-700">确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </main>
}

function PageTitle({eyebrow,title,desc}:{eyebrow:string,title:string,desc:string}){return <div className="mb-6"><p className="text-xs font-bold tracking-[.16em] text-[#0f8b7c]">{eyebrow}</p><h1 className="mt-1 text-3xl font-bold tracking-tight">{title}</h1><p className="mt-1 text-sm text-slate-500">{desc}</p></div>}
function Dashboard({items,stats,open,loading}:{items:ApplicationRecord[];stats:ReturnType<typeof calculateStats>;open:(x:ApplicationRecord)=>void;loading:boolean}){const cards=[["岗位总数",stats.jobCount,"包含待投递岗位"],["实际投递",stats.total,`回复率 ${stats.replyRate}%`],["进入面试",stats.interviews,`面试率 ${stats.interviewRate}%`],["获得 Offer",stats.offers,"记录每一个好消息"]];return <><PageTitle eyebrow="OVERVIEW" title="我的求职仪表盘" desc="今天要推进的申请和最近更新，一眼看清"/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([l,v,m])=><article key={l} className="rounded-2xl border border-[#d9e2ee] bg-white p-5 shadow-[0_8px_30px_rgba(28,45,75,.05)]"><p className="text-sm text-slate-500">{l}</p><div className="mt-3 flex items-end justify-between"><strong className="text-3xl">{v}</strong><span className="text-xs font-medium text-[#08796b]">{m}</span></div></article>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(280px,.7fr)]"><article className="rounded-2xl border border-[#d9e2ee] bg-white p-5"><h2 className="text-lg font-semibold">最近更新</h2><div className="mt-4 space-y-2">{loading?<p className="py-10 text-center text-slate-400">正在读取记录…</p>:items.slice(0,5).map(x=><button key={x.id} onClick={()=>open(x)} className="flex w-full items-center justify-between rounded-xl border border-transparent p-3 text-left hover:border-[#cde5e1] hover:bg-[#f6fcfb]"><div><p className="font-semibold">{x.company||"公司待确认"}</p><p className="text-sm text-slate-500">{x.position||"岗位待确认"} · {x.location||"地点待补充"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-medium ${statusStyle[x.status]}`}>{x.status}</span></button>)}</div></article><aside className="space-y-5"><article className="rounded-2xl bg-[#0d2547] p-5 text-white"><p className="text-sm text-blue-100">下一步建议</p><p className="mt-2 text-xl font-semibold">优先处理临近截止的岗位</p><p className="mt-3 text-sm leading-6 text-blue-100">资料库中补齐 JD 和准备笔记，面试前回看会更高效。</p></article><article className="rounded-2xl border border-[#bce9e1] bg-[#e9fbf7] p-5"><ChartNoAxesCombined className="text-[#08796b]"/><p className="mt-3 font-semibold text-[#07675c]">阶段分布</p><div className="mt-4 space-y-2">{STATUSES.slice(0,5).map(s=><div key={s} className="flex justify-between text-sm"><span>{s}</span><b>{items.filter(x=>x.status===s).length}</b></div>)}</div></article></aside></div></>}
function FilterBar(p:{query:string;setQuery:(x:string)=>void;status:string;setStatus:(x:string)=>void;category:string;setCategory:(x:string)=>void;location:string;setLocation:(x:string)=>void;sort:string;setSort:(x:string)=>void;locations:string[];categories:string[];exportCsv:()=>void;importCsv:()=>void}){return <div className="mb-5 rounded-2xl border border-[#d9e2ee] bg-white p-4"><div className="flex flex-wrap gap-3"><div className="relative min-w-[240px] flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><Input value={p.query} onChange={e=>p.setQuery(e.target.value)} placeholder="搜索公司、岗位、地点或备注" className="pl-9"/></div><Select value={p.status} onValueChange={p.setStatus}><SelectTrigger className="w-[145px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="全部状态">全部状态</SelectItem>{STATUSES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={p.category} onValueChange={p.setCategory}><SelectTrigger className="w-[145px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="全部类别">全部类别</SelectItem>{p.categories.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={p.location} onValueChange={p.setLocation}><SelectTrigger className="w-[145px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="全部地点">全部地点</SelectItem>{p.locations.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={p.sort} onValueChange={p.setSort}><SelectTrigger className="w-[145px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="updated">最近更新</SelectItem><SelectItem value="applied">投递日期</SelectItem><SelectItem value="company">公司名称</SelectItem></SelectContent></Select><Button variant="outline" onClick={p.importCsv} className="sm:hidden"><Upload/></Button><Button variant="outline" onClick={p.exportCsv}><Download/>导出</Button></div></div>}
function ApplicationList({items,loading,open,edit,remove,changeStatus}:{items:ApplicationRecord[];loading:boolean;open:(x:ApplicationRecord)=>void;edit:(x:ApplicationRecord)=>void;remove:(x:ApplicationRecord)=>void;changeStatus:(x:ApplicationRecord,s:string)=>void}){if(loading)return <div className="rounded-2xl border bg-white py-20 text-center text-slate-400">正在读取投递记录…</div>;if(!items.length)return <div className="rounded-2xl border border-dashed bg-white py-20 text-center"><BriefcaseBusiness className="mx-auto text-slate-300" size={38}/><p className="mt-3 font-semibold">没有符合条件的记录</p><p className="text-sm text-slate-500">调整筛选条件，或新增一条投递记录。</p></div>;return <div className="rounded-2xl border border-[#d9e2ee] bg-white shadow-[0_8px_30px_rgba(28,45,75,.04)]"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[820px] text-left text-sm"><thead><tr className="border-b bg-[#f8fafc] text-xs text-slate-500">{["公司与岗位","类别 / 地点","投递日期","当前进度","简历版本","操作"].map(x=><th key={x} className="px-5 py-3 font-medium">{x}</th>)}</tr></thead><tbody>{items.map(x=><tr key={x.id} className="border-b last:border-0 hover:bg-[#fbfdfd]"><td className="px-5 py-4"><button onClick={()=>open(x)} className="text-left"><p className="font-semibold">{x.company}</p><p className="text-slate-500">{x.position}</p></button></td><td className="px-5"><p>{x.category}</p><p className="text-slate-400">{x.location||"—"}</p></td><td className="px-5">{x.appliedDate||"未投递"}</td><td className="px-5"><select aria-label="更新进度" value={x.status} onChange={e=>changeStatus(x,e.target.value)} className={`rounded-full border-0 px-3 py-1 text-xs font-medium ${statusStyle[x.status]}`}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></td><td className="px-5 text-slate-500">{x.resumeVersion||"—"}</td><td className="px-5"><div className="flex gap-1"><Button variant="ghost" size="icon" aria-label="编辑" onClick={()=>edit(x)}><Pencil size={16}/></Button><Button variant="ghost" size="icon" aria-label="删除" onClick={()=>remove(x)}><Trash2 className="text-rose-500" size={16}/></Button></div></td></tr>)}</tbody></table></div><div className="divide-y md:hidden">{items.map(x=><article key={x.id} className="p-4"><button onClick={()=>open(x)} className="w-full text-left"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{x.company}</p><p className="text-sm text-slate-500">{x.position} · {x.location||"地点待补充"}</p></div><span className={`shrink-0 rounded-full px-3 py-1 text-xs ${statusStyle[x.status]}`}>{x.status}</span></div><p className="mt-3 text-xs text-slate-400">{x.appliedDate?`投递于 ${x.appliedDate}`:"尚未投递"} · {x.category}</p></button><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={()=>edit(x)}><Pencil/>编辑</Button><Button size="sm" variant="ghost" onClick={()=>remove(x)}><Trash2 className="text-rose-500"/>删除</Button></div></article>)}</div></div>}
function Library({items,open}:{items:ApplicationRecord[];open:(x:ApplicationRecord)=>void}){return <><PageTitle eyebrow="LIBRARY" title="岗位资料库" desc="JD、面试经验、笔试资料和准备笔记，按岗位归档"/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(x=>{const complete=[x.description,x.requirements,x.companyIntro,x.interviewExperience,x.preparationNotes].filter(Boolean).length;return <button key={x.id} onClick={()=>open(x)} className="rounded-2xl border border-[#d9e2ee] bg-white p-5 text-left shadow-[0_8px_30px_rgba(28,45,75,.04)] transition hover:-translate-y-0.5 hover:border-[#88d4c8]"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-[#e9fbf7] text-[#08796b]"><FileText/></span><span className="text-xs text-slate-400">{complete}/5 类资料</span></div><h2 className="mt-4 font-semibold">{x.company}</h2><p className="text-sm text-slate-500">{x.position}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-[#14b8a6]" style={{width:`${complete/5*100}%`}}/></div><p className="mt-4 line-clamp-2 text-sm leading-6 text-slate-600">{x.preparationNotes||x.description||"暂未添加岗位资料，点开后即可补充。"}</p></button>})}</div></>}

const fields=[["company","公司名称 *"],["position","岗位名称 *"],["category","岗位类别"],["location","工作地点"],["recruitmentType","招聘类型"],["source","信息来源"],["appliedDate","投递日期"],["deadline","截止日期"],["channel","投递渠道"],["status","当前进度"],["resumeVersion","简历版本"],["jobUrl","岗位链接"]] as const;
function ApplicationForm({value,close,save,saving}:{value:ApplicationRecord|null;close:()=>void;save:(x:ApplicationRecord)=>void;saving:boolean}){const [form,setForm]=useState(emptyApplication());useEffect(()=>{if(value)setForm(value)},[value]);const update=(key:keyof ApplicationRecord,val:string)=>setForm(x=>({...x,[key]:val}));return <Dialog open={!!value} onOpenChange={o=>!o&&close()}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{form.id?"编辑投递记录":"新增投递记录"}</DialogTitle><DialogDescription>先填写核心信息，岗位资料可以随时继续补充。</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();save(form)}} className="space-y-6"><div className="grid gap-4 sm:grid-cols-2">{fields.map(([key,label])=><div key={key} className={key==="jobUrl"?"sm:col-span-2":""}><Label htmlFor={key}>{label}</Label>{key==="category"?<Select value={form[key]} onValueChange={v=>update(key,v)}><SelectTrigger className="mt-1.5 w-full"><SelectValue/></SelectTrigger><SelectContent>{CATEGORIES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>:key==="status"?<Select value={form[key]} onValueChange={v=>update(key,v)}><SelectTrigger className="mt-1.5 w-full"><SelectValue/></SelectTrigger><SelectContent>{STATUSES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>:<Input id={key} type={key.includes("Date")||key==="deadline"?"date":key==="jobUrl"?"url":"text"} value={form[key]} onChange={e=>update(key,e.target.value)} className="mt-1.5"/>}</div>)}</div><Tabs defaultValue="jd"><TabsList className="grid w-full grid-cols-3"><TabsTrigger value="jd">岗位 JD</TabsTrigger><TabsTrigger value="resources">面试资料</TabsTrigger><TabsTrigger value="notes">笔记</TabsTrigger></TabsList><TabsContent value="jd" className="space-y-4 pt-3"><TextField label="岗位描述" value={form.description} onChange={v=>update("description",v)}/><TextField label="任职要求" value={form.requirements} onChange={v=>update("requirements",v)}/><TextField label="公司介绍" value={form.companyIntro} onChange={v=>update("companyIntro",v)}/></TabsContent><TabsContent value="resources" className="space-y-4 pt-3"><TextField label="面试经验" value={form.interviewExperience} onChange={v=>update("interviewExperience",v)}/><TextField label="笔试资料" value={form.writtenTestMaterials} onChange={v=>update("writtenTestMaterials",v)}/><TextField label="常见问题" value={form.commonQuestions} onChange={v=>update("commonQuestions",v)}/></TabsContent><TabsContent value="notes" className="space-y-4 pt-3"><TextField label="准备笔记" value={form.preparationNotes} onChange={v=>update("preparationNotes",v)}/><TextField label="备注" value={form.notes} onChange={v=>update("notes",v)}/></TabsContent></Tabs><div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={close}>取消</Button><Button disabled={saving||!form.company.trim()||!form.position.trim()}>{saving?"保存中…":"保存记录"}</Button></div></form></DialogContent></Dialog>}
function TextField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div><Label>{label}</Label><Textarea value={value} onChange={e=>onChange(e.target.value)} className="mt-1.5 min-h-24" placeholder={`填写${label}…`}/></div>}
function Detail({value,close,edit,optimize}:{value:ApplicationRecord|null;close:()=>void;edit:(x:ApplicationRecord)=>void;optimize:(x:ApplicationRecord)=>void}){if(!value)return null;const sections=[["公司介绍",value.companyIntro],["岗位描述",value.description],["任职要求",value.requirements],["面试经验",value.interviewExperience],["笔试资料",value.writtenTestMaterials],["常见问题",value.commonQuestions],["准备笔记",value.preparationNotes],["备注",value.notes]];return <Dialog open onOpenChange={o=>!o&&close()}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{value.company||"公司待确认"} · {value.position||"岗位待确认"}</DialogTitle><DialogDescription>{value.category} · {value.location||"地点待补充"} · 最后更新 {value.updatedAt?.slice(0,10)||"—"}</DialogDescription></DialogHeader><div className="flex flex-wrap gap-2"><span className={`rounded-full px-3 py-1 text-xs font-medium ${statusStyle[value.status]}`}>{value.status}</span>{value.isDraft&&<span className="rounded-full bg-amber-100 px-3 py-1 text-xs text-amber-800">草稿 · 待确认</span>}{value.appliedDate&&<span className="rounded-full bg-slate-100 px-3 py-1 text-xs">投递于 {value.appliedDate}</span>}{value.deadline&&<span className="rounded-full bg-rose-50 px-3 py-1 text-xs text-rose-700">截止 {value.deadline}</span>}</div>{value.applicationId&&<div className="rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm"><b>本次投递使用的简历：</b>{value.resumeVersion||"尚未关联"}</div>}<div className="grid gap-4 sm:grid-cols-2">{sections.map(([title,content])=><section key={title} className="rounded-xl border border-[#e2e8f0] p-4"><h3 className="font-semibold">{title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{content||"暂未填写"}</p></section>)}</div>{value.jobUrl&&<a href={value.jobUrl} target="_blank" rel="noreferrer" className="text-sm font-medium text-[#08796b] underline">打开原始岗位链接</a>}<div className="flex flex-wrap justify-end gap-2"><Button variant="outline" disabled={!value.description&&!value.requirements} onClick={()=>optimize(value)}><Sparkles/>针对该岗位优化简历</Button><Button onClick={()=>edit(value)}><Pencil/>编辑资料</Button></div></DialogContent></Dialog>}
